nosh and (define (midpoint-1)
  (let-geo* ((a (random-point))
             (b (random-point))
             (s (segment a b))
             (m (segment-midpoint s)))
            (figure a b s m)))

(define (midpoint-2)
  (let-geo* ((s (random-segment))
             (m (segment-midpoint s)))
            (figure s m)))

(define (circle-radius)
  (let-geo* ((c (random-circle))
             (r1 (random-circle-radius c))
             (r2 (random-circle-radius c)))
            (figure c r1 r2)))
