;;; load.scm -- Load figure
(for-each (lambda (f) (load f))
          '("core"
            "metadata"
            "linear"
            "direction"
            "direction-interval"
            "vec"
            "measurements"
            "angle"
            "bounds"
            "circle"
            "point"
            "constructions"
            "intersections"
            "figure"
            "math-utils"
            "polygon"
            "dependencies"
            "randomness"
            "transforms"))
